# Generated by Django 3.0.3 on 2020-08-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recom_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_info',
            name='organizer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
