# Generated by Django 3.0.3 on 2020-08-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recom_api', '0002_auto_20200802_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_info',
            name='rank_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
